#!/usr/bin/env node

import { cpSync, existsSync, mkdtempSync, readdirSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join, resolve } from "node:path";
import { spawnSync } from "node:child_process";
import { fileURLToPath } from "node:url";

const DEFAULT_OWNER_REPO = "CreeperLKF/Endfieldize";
const DEFAULT_BRANCH = "cdn";
const DEFAULT_REMOTE = "origin";

export function normalizeVersion(rawVersion) {
  const version = String(rawVersion ?? "").trim().replace(/^v/, "");

  if (!/^\d+\.\d+\.\d+(?:-[0-9A-Za-z.-]+)?(?:\+[0-9A-Za-z.-]+)?$/.test(version)) {
    throw new Error(`Expected a semver release like 1.2.3 or v1.2.3, received: ${rawVersion}`);
  }

  return version;
}

export function versionTagFor(rawVersion) {
  return `v${normalizeVersion(rawVersion)}`;
}

export function cdnBaseForVersion(rawVersion, options = {}) {
  const ownerRepo = options.ownerRepo ?? DEFAULT_OWNER_REPO;
  const branch = options.branch ?? DEFAULT_BRANCH;

  return `https://cdn.jsdelivr.net/gh/${ownerRepo}@${branch}/${versionTagFor(rawVersion)}/`;
}

export function createReleasePlan(rawVersion, options = {}) {
  const version = normalizeVersion(rawVersion);
  const versionTag = versionTagFor(version);
  const branch = options.branch ?? DEFAULT_BRANCH;

  return {
    version,
    versionTag,
    branch,
    remote: options.remote ?? DEFAULT_REMOTE,
    ownerRepo: options.ownerRepo ?? DEFAULT_OWNER_REPO,
    releaseDir: versionTag,
    buildOutDir: options.buildOutDir ?? `.cdn-dist/${versionTag}`,
    cdnBaseUrl: cdnBaseForVersion(version, {
      branch,
      ownerRepo: options.ownerRepo ?? DEFAULT_OWNER_REPO,
    }),
  };
}

function run(command, args, options = {}) {
  const result = spawnSync(command, args, {
    cwd: options.cwd,
    env: options.env,
    encoding: "utf8",
    stdio: options.capture ? "pipe" : "inherit",
  });

  if (result.error) {
    throw result.error;
  }

  if (result.status !== 0) {
    throw new Error(`${command} ${args.join(" ")} failed with exit code ${result.status}`);
  }

  return result.stdout?.trim() ?? "";
}

function tryRun(command, args, options = {}) {
  return spawnSync(command, args, {
    cwd: options.cwd,
    encoding: "utf8",
    stdio: "pipe",
  });
}

function readPackageVersion() {
  const packageJson = JSON.parse(readFileSync("package.json", "utf8"));
  return normalizeVersion(packageJson.version);
}

function remoteUrl(remote) {
  return run("git", ["remote", "get-url", remote], { capture: true });
}

function renderCdnReadme(plan, releaseDirs) {
  const releaseRows = releaseDirs
    .map((dir) => `- ${dir}: https://cdn.jsdelivr.net/gh/${plan.ownerRepo}@${plan.branch}/${dir}/`)
    .join("\n");

  return `# Endfieldize CDN Assets

This branch is generated by \`npm run release:cdn -- <version> --publish\`.

## Releases

${releaseRows}
`;
}

function parseCliArgs(argv) {
  const options = {
    publish: false,
    branch: DEFAULT_BRANCH,
    remote: DEFAULT_REMOTE,
    ownerRepo: DEFAULT_OWNER_REPO,
  };
  const positional = [];

  for (let index = 0; index < argv.length; index += 1) {
    const arg = argv[index];

    if (arg === "--publish") {
      options.publish = true;
    } else if (arg === "--branch") {
      options.branch = argv[++index];
    } else if (arg === "--remote") {
      options.remote = argv[++index];
    } else if (arg === "--owner-repo") {
      options.ownerRepo = argv[++index];
    } else {
      positional.push(arg);
    }
  }

  if (!positional[0]) {
    throw new Error("Usage: npm run release:cdn -- <version> [--publish]");
  }

  return { version: positional[0], options };
}

function publishCdnBranch(plan) {
  const buildDir = resolve(plan.buildOutDir);
  if (!existsSync(buildDir)) {
    throw new Error(`Expected CDN build output at ${plan.buildOutDir}`);
  }

  const tempRepo = mkdtempSync(join(tmpdir(), "endfieldize-cdn-"));
  const releaseTarget = join(tempRepo, plan.releaseDir);

  run("git", ["init", "-b", plan.branch], { cwd: tempRepo });
  run("git", ["remote", "add", "origin", remoteUrl(plan.remote)], { cwd: tempRepo });

  const fetch = tryRun("git", ["fetch", "--depth", "1", "origin", plan.branch], { cwd: tempRepo });
  if (fetch.status === 0) {
    run("git", ["reset", "--hard", "FETCH_HEAD"], { cwd: tempRepo });
  }

  if (existsSync(releaseTarget)) {
    throw new Error(`${plan.branch}/${plan.releaseDir} already exists. Bump the version instead of overwriting CDN assets.`);
  }

  cpSync(buildDir, releaseTarget, { recursive: true });

  const releaseDirs = readdirSync(tempRepo)
    .filter((entry) => /^v\d+\.\d+\.\d+/.test(entry))
    .sort();
  writeFileSync(join(tempRepo, "README.md"), renderCdnReadme(plan, releaseDirs));

  run("git", ["add", "README.md", plan.releaseDir], { cwd: tempRepo });
  run("git", ["commit", "-m", `Publish CDN assets for ${plan.versionTag}`], { cwd: tempRepo });

  if (plan.publish) {
    run("git", ["push", "origin", `${plan.branch}:${plan.branch}`], { cwd: tempRepo });
    rmSync(tempRepo, { recursive: true, force: true });
  } else {
    console.log(`CDN release branch prepared at ${tempRepo}`);
    console.log(`Run this to publish: git -C ${tempRepo} push origin ${plan.branch}:${plan.branch}`);
  }
}

function main() {
  const { version, options } = parseCliArgs(process.argv.slice(2));
  const plan = {
    ...createReleasePlan(version, options),
    publish: options.publish,
  };

  const packageVersion = readPackageVersion();
  if (packageVersion !== plan.version) {
    throw new Error(`package.json version is ${packageVersion}, but the requested release is ${plan.version}`);
  }

  console.log(`Preparing ${plan.versionTag} for ${plan.cdnBaseUrl}`);

  run("npm", ["test"]);
  run("npm", ["run", "build:cdn"], {
    env: {
      ...process.env,
      ENDFIELDIZE_CDN_BASE: plan.cdnBaseUrl,
      ENDFIELDIZE_CDN_OUT_DIR: plan.buildOutDir,
    },
  });
  publishCdnBranch(plan);
}

function isMainModule() {
  return process.argv[1] === fileURLToPath(import.meta.url);
}

if (isMainModule()) {
  try {
    main();
  } catch (error) {
    console.error(error instanceof Error ? error.message : error);
    process.exit(1);
  }
}
